Deny use of tcb command with password-based SSH
We use multiple invocations of SSH-based tools to set up call-buddy in a
remote environment as well as use rsync on a timer to sync new data
down. However, if we allow password-based SSH, the user will have to
enter their password multiple times before even launching into the
remote environment and once there, syncing will not work since they will
not be able to enter their password in.

This is very unfortunate since not all machines you want to connect to
have passwordless SSH set up and setting one up adds a lot of friction.
As far as I'm aware this is by the nature of shell commands and there's
no shell-based alternative that I'm aware of. :(

If I had more time, I'd possibly consider replacing the utility with a
golang based one where I could invoke multiple operations in the same
SSH session, but it's not worth my time at this point.

diff --git a/tcb b/tcb
--- a/tcb
+++ b/tcb
@@ -75,6 +75,19 @@ if test $? -ne 0; then
     exit $?
 fi
 
+printf "Checking if SSH is passwordless... " > /dev/stderr
+if ! $(ssh -o PreferredAuthentications=publickey,hostbased "$target" /bin/true); then
+    # We can't really allow password-based SSH since not only do we require
+    # multiple invocations of SSH-based commands to sync and set up call-buddy
+    # (which would require entering passwords many times), but syncing will
+    # also not work which is half the point of this script.
+    #
+    # This sucks, but I'm not sure of a better way to do this...
+    die "Could not SSH to '$target' without password. Cannot proceed."
+fi
+echo
+
+
 printf "Looking up architecture..." > /dev/stderr
 arch="$(ssh "$target" "uname -s -m | tr ' ' '-' | tr '[:upper:]' '[:lower:]'")"
 if [ "$arch" = "" ]; then
